### ISSUE TITLE
really need a serious xml builder

### ISSUE THREAD

**Issue by CicholGricenchos** [bjjb/ebayr#16]
`{"Name"=>"Color", "Value"=>["Black", "Pink", "Yellow", "Blue"]}` went in
and
`<Name>Color</Name><Value>BlackPinkYellowBlue</Value>` went out

which should be
`<Name>Color</Name><Value>Black</Value><Value>Pink</Value><Value>Yellow</Value><Value>Blue</Value>`

why not try ActiveSupport or something?

**Comment by CicholGricenchos** [comment]
well, i see

you prefer another way to handle that array params, to input
`{"Name"=>"Color", [{"Value"=>"Black"}, {"Value"=>"Pink"}, {"Value"=>"Yellow"}, {"Value"=>"Blue"}]}`

ummm, but this is not so common...

i would like to have my own fork :-(

**Comment by SpeerJ** [comment]
looking through the forks i found this commit https://github.com/meismann/ebayr/commit/d7c46e2c3e56c6dd40350fcaac5e35bec4a05505

**Comment by SpeerJ** [comment]
Look's ready to go except that the hash's use the ruby 1.9 syntax "{asdf: 1}." We target 1.8.3+

**Comment by bjjb** [comment]
I disagree with the title of the issue, @CicholGricenchos - "need" is too strong a word. Of course I started with XML builder libraries (nobody with any experience writes XML processors without good reason); if you dig through the history, you might find some old versions that used various libraries (including ActiveSupport, Nokogiri::XML::Builder, and even REXML). I systematically abandoned them one by one, for various reasons (poor Ruby version compatibility, inappropriate APIs, or way too many gem dependencies). Eventually I determined that the more reasonable course of action for the very predictable XML output requirements of eBayR was a (thoroughly tested), bare-bones custom job.

So I need to be convinced. Please feel free to fork the project, and if a pull request comes in which replaced eBayR's built-in XML processors, provably works on all Ruby version **from 1.8.7 onwards**, includes benchmarks indicating a significant speedup, and has the support of the other developers, I'll of course be quite happy to merge it into master and release a new version.

**Comment by CicholGricenchos** [comment]
Sorry for that phrasing, since I don't daily use English..
I knew more about the situation now, thank you and your post!

**Comment by bjjb** [comment]
You're welcome, @CicholGricenchos, and it's a credit to your English that I didn't notice you weren't a native speaker. :gb:
