### ISSUE TITLE
Not able to add attributes on tags

### ISSUE THREAD

**Issue by GCorbel** [bjjb/ebayr#23]
As you can see in [the doc](http://developer.ebay.com/devzone/XML/docs/Reference/eBay/AddOrder.html#AddOrder) some tag needs attributes. For example, `<Total currencyID="CurrencyCodeType"> AmountType (double) </Total>`.

I tried to do this : 

`Ebayr::Request.new(:AddOrder, input: [{ Order: { CreatingUserRole: 'Buyer', 'Total' => 100 } }]).send`

And I have this result : 

```
{:xmlns=>"urn:ebay:apis:eBLBaseComponents",
 :timestamp=>"2016-04-04T19:49:15.014Z",
 :ack=>"Failure",
 :errors=>
  [{:short_message=>"No <Order.Total.CurrencyID> exists or <Order.Total.CurrencyID> is specified as an empty tag.",
    :long_message=>
     "No <Order.Total.CurrencyID> exists or <Order.Total.CurrencyID> is specified as an empty tag in the request.",
    :error_code=>"10009",
    :severity_code=>"Error",
    :error_parameters=>{:param_id=>"0", :value=>"Order.Total.CurrencyID"},
    :error_classification=>"RequestError"},
   {:short_message=>"No <Order.TransactionArray> exists or <Order.TransactionArray> is specified as an empty tag.",
    :long_message=>
     "No <Order.TransactionArray> exists or <Order.TransactionArray> is specified as an empty tag in the request.",
    :error_code=>"10009",
    :severity_code=>"Error",
    :error_parameters=>{:param_id=>"0", :value=>"Order.TransactionArray"},
    :error_classification=>"RequestError"}],
 :version=>"949",
 :build=>"E949_CORE_API_17895653_R1"}
```

By reading the code, [at this line](https://github.com/bjjb/ebayr/blob/master/lib/ebayr/request.rb#L101), is see there is no way to do. I propose to do a Pull Request with a format like : 

`Ebayr::Request.new(:AddOrder, input: [{ Order: { CreatingUserRole: 'Buyer', 'Total' => { value : 100, attr: { CurrencyID: 'EUR' } } }]).send`

What you think ?

**Comment by bjjb** [comment]
Looks like a good idea to me, @GCorbel . If the Travis CI build passes, then I'm happy to accept.

**Comment by GCorbel** [comment]
I don't why it doesn't pass. I have this weird error message : `An error occurred while installing rake (11.1.2), and Bundler cannot continue.`. Maybe a rebuild will work  but I can't do it.

**Comment by spk** [comment]
Hi @bjjb look like the changes are not related since its errors with old Rubies:

* `Gem::InstallError: rake requires Ruby version >= 1.9.3.`, cf https://travis-ci.org/bjjb/ebayr/jobs/120736828#L191
* `NoMethodError: undefined method `spec' for nil:NilClass`, cf https://travis-ci.org/bjjb/ebayr/jobs/120736827#L177

Are you interested in a PR fixing that ?

**Comment by bjjb** [comment]
Hmm, I wonder how many people are using 1.8? Maybe there's stats available from Rubygems. If you want to remind me later in the week, I can look into it. And if the usage is negligible (I recently retired a ruby 1.8 ebayr project), then I'd be happy to only support >= 1.9.3. It would need a post-install message and a new minor version.

**Comment by spk** [comment]
Support for 1.8 is over for a long time now and 1.9 also but still largely used (https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/)

**Comment by bjjb** [comment]
@spk Sure, I'd welcome a PR.

**Comment by spk** [comment]
Hi @bjjb all green on #27 !
