### ISSUE TITLE
Not Able to add PictureURL for AddFixedPriceItem

### ISSUE THREAD

**Issue by webmaster219** [bjjb/ebayr#26]
In this function requires like this
"<PictureDetails>PictureDetails
      <GalleryDuration> GalleryDuration:token </GalleryDuration>
      <GalleryType>GalleryType: GalleryTypeCodeType </GalleryType>
      <GalleryURL> GalleryURL:anyURI </GalleryURL>
      <PhotoDisplay>PhotoDisplay: PhotoDisplayCodeType </PhotoDisplay>
      <PictureSource>PictureSource: PictureSourceCodeType </PictureSource>
      <PictureURL> anyPictureURL1 </PictureURL>
      <PictureURL> anyPictureURL1 </PictureURL>
      <PictureURL> anyPictureURL1 </PictureURL>
      
    </PictureDetails>"
How can I add this PicturURL on calling apis option?

**Comment by webmaster219** [comment]
Hi

**Comment by neverender** [comment]
So... any ideas about this? We need multiple PictureURL's but a Hash can't have duplicate keys. If I try an array like:
`PictureURL:`` ['url1', 'url2']

you have it doing:
`<PictureURL>url1url2</PictureURL>`

What we need is 
`<PictureURL>url1</PictureURL><PictureURL>url2</PictureURL>`

**Comment by neverender** [comment]
Ah. I found a solution using [Hash#compare_by_identity](http://www.rubydoc.info/stdlib/core/Hash%3Acompare_by_identity) to allow duplicate keys.

**Comment by yasuhisa1984** [comment]
Hi.I also encountered the same problem.
That's the following manner, it will become a type error.

"PictureDetails"=>
 [{"GalleryType"=>["Gallery"],
   "GalleryURL"=>["http://i.ebayimg.com/00/s/NDM2WDUwMA==/z/TIsAAOSwHMJYHCQc/$_3.JPG"],
   "PictureURL"=>[{"url"=>"http://i.ebayimg.com/00/s/NTAwWDMzNw==/z/06EAAOSw5cNYHCQd/$_3.JPG", "url2"=>"http://i.ebayimg.com/00/s/NTAwWDMzNA==/z/lNMAAOSwKOJYHCQl/$_3.JPG"}]}]}]

**Comment by bjjb** [comment]
Hi @neverender, @yasuhisa1984 (sorry about the late response), is this still an issue for you folks?

**Comment by yasuhisa1984** [comment]
@bjjb I am still suffering. If there is a solution, I am glad.

**Comment by yasuhisa1984** [comment]
I solved it using compare_by_identity. (Hash#compare_by_identity)
I should change object.id.
Thank you.

**Comment by bjjb** [comment]
Good job, @neverender .
