### ISSUE TITLE
Not able to add multiple media attachments

### ISSUE THREAD

**Issue by sathishceg** [bjjb/ebayr#9]
Not able to add multiple media attachments for AddMemberMessageRTQ api call...Below is my api call

Ebayr.call(:AddMemberMessageRTQ,:ItemID => "******" ,:MemberMessage => {:Body => Test, :MessageMedia => {:MediaName => "Test1",:MediaURL => "URL1"}, :MessageMedia => {:MediaName => "Test2",:MediaURL => "URL2"}, :ParentMessageID=> "ID" , :RecipientID=> "ID" })

**Comment by bjjb** [comment]
Did you try a single `MessageMedia` key with an array? With your call above, the second reference simply overwrites the first. You could try playing around with the method [here](https://github.com/bjjb/ebayr/blob/master/lib/ebayr/request.rb#L85) and see whether [the test](https://github.com/bjjb/ebayr/blob/master/test/ebayr/request_test.rb#L40) checks your requirements.

**Comment by sathishfreshdesk** [comment]
Yes i tried an array with multiple MessageMedia object but still it constructs only a single MessageMedia...

**Comment by bjjb** [comment]
Weird. Can you post some code?

**Comment by neilturner77** [comment]
Was this ever fixed? I'm running into the same problem with the :PaymentMethods option (it's repeatable) but obviously you can't have 2 hash keys the same.

**Comment by neilturner77** [comment]
Oh, and if I try passing an array as the argument for :PaymentMethods it concats the two values into a single string i.e. <PaymentMethods>CreditCardPayPal</PaymentMethods>.

**Comment by bjjb** [comment]
@neilturner77 - [this test](https://github.com/bjjb/ebayr/blob/master/test/ebayr/request_test.rb#L40) checks for that, and it's passing. Got some code?

**Comment by sathishceg** [comment]
Hi can you please give a sample on how to build multiple xml nodes for the outout selector.I am unable to build multiple OutputSelector...

Here is the code which i am using:

Ebayr.call(:GetItem, :DetailLevel => "ReturnAll", :ItemID => "ID", :OutputSelector => "PrimaryCategory",:OutputSelector => "SellingStatus")


Please provide a sample for the above...

**Comment by SpeerJ** [comment]
hey bjjb i think the problem is that you test only check that self.xml can return a correct xml string. Whats happening here is that we are unable to insert a array dirrectly into the option hash eg({foo: 1, bar: 2, [{media: }]}). If we pass it only an array, delete can't select the hashes out of the array.

**Comment by SpeerJ** [comment]
bjjb: issued a pull request.

**Comment by SpeerJ** [comment]
@sathishceg @neilturner77  if you want to try my proposed patch you can get it with:
 git clone https://github.com/SpeerJ/ebayr.git --branch patch-1 --single-branch
then enter the folder and build with:
gem build ebayr.gemspec 
then install with:
gem install ebayr*.gem

the syntax is Ebayr.call(:call_name, :any_keywords, input: [{any_xml: xml_value}, {any_xml: xml_value}])

for example sathishceg's call would be Ebayr.call(:GetItem, input: [{:DetailLevel => "ReturnAll"}, {:ItemID => "ID"},{:OutputSelector => "PrimaryCategory"},{:OutputSelector => "SellingStatus"}])
